// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: events_monitoring/v1/events.proto

package com.parrothq.events_monitoring.v1;

public interface EventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:events_monitoring.v1.Event)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.events_monitoring.v1.Header header = 1;</code>
   * @return Whether the header field is set.
   */
  boolean hasHeader();
  /**
   * <code>.events_monitoring.v1.Header header = 1;</code>
   * @return The header.
   */
  com.parrothq.events_monitoring.v1.Header getHeader();
  /**
   * <code>.events_monitoring.v1.Header header = 1;</code>
   */
  com.parrothq.events_monitoring.v1.HeaderOrBuilder getHeaderOrBuilder();

  /**
   * <code>.google.protobuf.Any spec = 2;</code>
   * @return Whether the spec field is set.
   */
  boolean hasSpec();
  /**
   * <code>.google.protobuf.Any spec = 2;</code>
   * @return The spec.
   */
  com.google.protobuf.Any getSpec();
  /**
   * <code>.google.protobuf.Any spec = 2;</code>
   */
  com.google.protobuf.AnyOrBuilder getSpecOrBuilder();
}
