# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events_monitoring/v1/expectations.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='events_monitoring/v1/expectations.proto',
  package='events_monitoring.v1',
  syntax='proto3',
  serialized_options=b'\n!com.parrothq.events_monitoring.v1P\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\'events_monitoring/v1/expectations.proto\x12\x14\x65vents_monitoring.v1\"t\n\x1dRecordingPreprocessingStarted\x12\x1c\n\x14\x61udio_length_seconds\x18\x01 \x01(\x05\x12\x35\n\x06source\x18\x02 \x01(\x0e\x32%.events_monitoring.v1.RecordingSource\"#\n!LiveTranscriptRoughDraftCompleted\"\x15\n\x13RoughDraftCompleted\"!\n\x1fRoughDraftWithSpeakersCompleted*F\n\x0fRecordingSource\x12\x1c\n\x18RECORDING_SOURCE_UNKNOWN\x10\x00\x12\n\n\x06UPLOAD\x10\x01\x12\t\n\x05\x45VENT\x10\x02\x42%\n!com.parrothq.events_monitoring.v1P\x01\x62\x06proto3'
)

_RECORDINGSOURCE = _descriptor.EnumDescriptor(
  name='RecordingSource',
  full_name='events_monitoring.v1.RecordingSource',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RECORDING_SOURCE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UPLOAD', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EVENT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=278,
  serialized_end=348,
)
_sym_db.RegisterEnumDescriptor(_RECORDINGSOURCE)

RecordingSource = enum_type_wrapper.EnumTypeWrapper(_RECORDINGSOURCE)
RECORDING_SOURCE_UNKNOWN = 0
UPLOAD = 1
EVENT = 2



_RECORDINGPREPROCESSINGSTARTED = _descriptor.Descriptor(
  name='RecordingPreprocessingStarted',
  full_name='events_monitoring.v1.RecordingPreprocessingStarted',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='audio_length_seconds', full_name='events_monitoring.v1.RecordingPreprocessingStarted.audio_length_seconds', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source', full_name='events_monitoring.v1.RecordingPreprocessingStarted.source', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=181,
)


_LIVETRANSCRIPTROUGHDRAFTCOMPLETED = _descriptor.Descriptor(
  name='LiveTranscriptRoughDraftCompleted',
  full_name='events_monitoring.v1.LiveTranscriptRoughDraftCompleted',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=218,
)


_ROUGHDRAFTCOMPLETED = _descriptor.Descriptor(
  name='RoughDraftCompleted',
  full_name='events_monitoring.v1.RoughDraftCompleted',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=220,
  serialized_end=241,
)


_ROUGHDRAFTWITHSPEAKERSCOMPLETED = _descriptor.Descriptor(
  name='RoughDraftWithSpeakersCompleted',
  full_name='events_monitoring.v1.RoughDraftWithSpeakersCompleted',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=276,
)

_RECORDINGPREPROCESSINGSTARTED.fields_by_name['source'].enum_type = _RECORDINGSOURCE
DESCRIPTOR.message_types_by_name['RecordingPreprocessingStarted'] = _RECORDINGPREPROCESSINGSTARTED
DESCRIPTOR.message_types_by_name['LiveTranscriptRoughDraftCompleted'] = _LIVETRANSCRIPTROUGHDRAFTCOMPLETED
DESCRIPTOR.message_types_by_name['RoughDraftCompleted'] = _ROUGHDRAFTCOMPLETED
DESCRIPTOR.message_types_by_name['RoughDraftWithSpeakersCompleted'] = _ROUGHDRAFTWITHSPEAKERSCOMPLETED
DESCRIPTOR.enum_types_by_name['RecordingSource'] = _RECORDINGSOURCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecordingPreprocessingStarted = _reflection.GeneratedProtocolMessageType('RecordingPreprocessingStarted', (_message.Message,), {
  'DESCRIPTOR' : _RECORDINGPREPROCESSINGSTARTED,
  '__module__' : 'events_monitoring.v1.expectations_pb2'
  # @@protoc_insertion_point(class_scope:events_monitoring.v1.RecordingPreprocessingStarted)
  })
_sym_db.RegisterMessage(RecordingPreprocessingStarted)

LiveTranscriptRoughDraftCompleted = _reflection.GeneratedProtocolMessageType('LiveTranscriptRoughDraftCompleted', (_message.Message,), {
  'DESCRIPTOR' : _LIVETRANSCRIPTROUGHDRAFTCOMPLETED,
  '__module__' : 'events_monitoring.v1.expectations_pb2'
  # @@protoc_insertion_point(class_scope:events_monitoring.v1.LiveTranscriptRoughDraftCompleted)
  })
_sym_db.RegisterMessage(LiveTranscriptRoughDraftCompleted)

RoughDraftCompleted = _reflection.GeneratedProtocolMessageType('RoughDraftCompleted', (_message.Message,), {
  'DESCRIPTOR' : _ROUGHDRAFTCOMPLETED,
  '__module__' : 'events_monitoring.v1.expectations_pb2'
  # @@protoc_insertion_point(class_scope:events_monitoring.v1.RoughDraftCompleted)
  })
_sym_db.RegisterMessage(RoughDraftCompleted)

RoughDraftWithSpeakersCompleted = _reflection.GeneratedProtocolMessageType('RoughDraftWithSpeakersCompleted', (_message.Message,), {
  'DESCRIPTOR' : _ROUGHDRAFTWITHSPEAKERSCOMPLETED,
  '__module__' : 'events_monitoring.v1.expectations_pb2'
  # @@protoc_insertion_point(class_scope:events_monitoring.v1.RoughDraftWithSpeakersCompleted)
  })
_sym_db.RegisterMessage(RoughDraftWithSpeakersCompleted)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
