// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: events_monitoring/v1/expectations.proto

package com.parrothq.events_monitoring.v1;

public interface ComputeWaveformCompletedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:events_monitoring.v1.ComputeWaveformCompleted)
    com.google.protobuf.MessageOrBuilder {
}
