// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: events_monitoring/v1/expectations.proto

package com.parrothq.events_monitoring.v1;

public interface EndDiarizedRoughDraftOrBuilder extends
    // @@protoc_insertion_point(interface_extends:events_monitoring.v1.EndDiarizedRoughDraft)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string recording_id = 1;</code>
   * @return The recordingId.
   */
  java.lang.String getRecordingId();
  /**
   * <code>string recording_id = 1;</code>
   * @return The bytes for recordingId.
   */
  com.google.protobuf.ByteString
      getRecordingIdBytes();
}
