// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parrotschemas/events_monitoring/v1/events.proto

package com.parrothq.events_monitoring.v1;

public final class Events {
  private Events() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_parrotschemas_events_monitoring_v1_Header_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_parrotschemas_events_monitoring_v1_Header_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_parrotschemas_events_monitoring_v1_Event_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_parrotschemas_events_monitoring_v1_Event_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/parrotschemas/events_monitoring/v1/eve" +
      "nts.proto\022\"parrotschemas.events_monitori" +
      "ng.v1\032\031google/protobuf/any.proto\032\037google" +
      "/protobuf/timestamp.proto\"s\n\006Header\022\022\n\ne" +
      "vent_type\030\001 \001(\t\022\026\n\016correlation_id\030\002 \001(\t\022" +
      "-\n\ttimestamp\030\003 \001(\0132\032.google.protobuf.Tim" +
      "estamp\022\016\n\006silent\030\004 \001(\010\"\244\001\n\005Event\022:\n\006head" +
      "er\030\001 \001(\0132*.parrotschemas.events_monitori" +
      "ng.v1.Header\022\"\n\004spec\030\002 \001(\0132\024.google.prot" +
      "obuf.Any\022;\n\004type\030\003 \001(\0162-.parrotschemas.e" +
      "vents_monitoring.v1.EventType*:\n\tEventTy" +
      "pe\022\026\n\022EVENT_TYPE_UNKNOWN\020\000\022\n\n\006NORMAL\020\001\022\t" +
      "\n\005ERROR\020\002B%\n!com.parrothq.events_monitor" +
      "ing.v1P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_parrotschemas_events_monitoring_v1_Header_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_parrotschemas_events_monitoring_v1_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_parrotschemas_events_monitoring_v1_Header_descriptor,
        new java.lang.String[] { "EventType", "CorrelationId", "Timestamp", "Silent", });
    internal_static_parrotschemas_events_monitoring_v1_Event_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_parrotschemas_events_monitoring_v1_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_parrotschemas_events_monitoring_v1_Event_descriptor,
        new java.lang.String[] { "Header", "Spec", "Type", });
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
