// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: events_monitoring/v1/events.proto

package com.parrothq.events_monitoring.v1;

public final class Events {
  private Events() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_events_monitoring_v1_Header_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_events_monitoring_v1_Header_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_events_monitoring_v1_Event_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_events_monitoring_v1_Event_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!events_monitoring/v1/events.proto\022\024eve" +
      "nts_monitoring.v1\032\031google/protobuf/any.p" +
      "roto\032\037google/protobuf/timestamp.proto\"K\n" +
      "\006Header\022\022\n\nevent_type\030\001 \001(\t\022-\n\ttimestamp" +
      "\030\002 \001(\0132\032.google.protobuf.Timestamp\"Y\n\005Ev" +
      "ent\022,\n\006header\030\001 \001(\0132\034.events_monitoring." +
      "v1.Header\022\"\n\004spec\030\002 \001(\0132\024.google.protobu" +
      "f.AnyB%\n!com.parrothq.events_monitoring." +
      "v1P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_events_monitoring_v1_Header_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_events_monitoring_v1_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_events_monitoring_v1_Header_descriptor,
        new java.lang.String[] { "EventType", "Timestamp", });
    internal_static_events_monitoring_v1_Event_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_events_monitoring_v1_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_events_monitoring_v1_Event_descriptor,
        new java.lang.String[] { "Header", "Spec", });
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
