// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: events_monitoring/v1/expectations.proto

package com.parrothq.events_monitoring.v1;

public final class Expectations {
  private Expectations() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_events_monitoring_v1_StartRoughDraft_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_events_monitoring_v1_StartRoughDraft_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_events_monitoring_v1_EndRoughDraft_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_events_monitoring_v1_EndRoughDraft_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'events_monitoring/v1/expectations.prot" +
      "o\022\024events_monitoring.v1\"=\n\017StartRoughDra" +
      "ft\022\024\n\014recording_id\030\001 \001(\t\022\024\n\014audio_length" +
      "\030\002 \001(\005\"%\n\rEndRoughDraft\022\024\n\014recording_id\030" +
      "\001 \001(\tB%\n!com.parrothq.events_monitoring." +
      "v1P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_events_monitoring_v1_StartRoughDraft_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_events_monitoring_v1_StartRoughDraft_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_events_monitoring_v1_StartRoughDraft_descriptor,
        new java.lang.String[] { "RecordingId", "AudioLength", });
    internal_static_events_monitoring_v1_EndRoughDraft_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_events_monitoring_v1_EndRoughDraft_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_events_monitoring_v1_EndRoughDraft_descriptor,
        new java.lang.String[] { "RecordingId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
