// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parrotschemas/events_monitoring/v1/expectations.proto

package com.parrothq.events_monitoring.v1;

public interface GenerateDocumentsCompletedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:parrotschemas.events_monitoring.v1.GenerateDocumentsCompleted)
    com.google.protobuf.MessageOrBuilder {
}
