// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: events_monitoring/v1/events.proto

package com.parrothq.events_monitoring.v1;

public interface HeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:events_monitoring.v1.Header)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string event_type = 1;</code>
   * @return The eventType.
   */
  java.lang.String getEventType();
  /**
   * <code>string event_type = 1;</code>
   * @return The bytes for eventType.
   */
  com.google.protobuf.ByteString
      getEventTypeBytes();

  /**
   * <code>string correlation_id = 2;</code>
   * @return The correlationId.
   */
  java.lang.String getCorrelationId();
  /**
   * <code>string correlation_id = 2;</code>
   * @return The bytes for correlationId.
   */
  com.google.protobuf.ByteString
      getCorrelationIdBytes();

  /**
   * <code>.google.protobuf.Timestamp timestamp = 3;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 3;</code>
   * @return The timestamp.
   */
  com.google.protobuf.Timestamp getTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

  /**
   * <code>bool silent = 4;</code>
   * @return The silent.
   */
  boolean getSilent();
}
