// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: events_monitoring/v1/expectations.proto

package com.parrothq.events_monitoring.v1;

/**
 * Protobuf enum {@code events_monitoring.v1.RecordingSource}
 */
public enum RecordingSource
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>RECORDING_SOURCE_UNKNOWN = 0;</code>
   */
  RECORDING_SOURCE_UNKNOWN(0),
  /**
   * <code>UPLOAD = 1;</code>
   */
  UPLOAD(1),
  /**
   * <code>DEPOSITION = 2;</code>
   */
  DEPOSITION(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>RECORDING_SOURCE_UNKNOWN = 0;</code>
   */
  public static final int RECORDING_SOURCE_UNKNOWN_VALUE = 0;
  /**
   * <code>UPLOAD = 1;</code>
   */
  public static final int UPLOAD_VALUE = 1;
  /**
   * <code>DEPOSITION = 2;</code>
   */
  public static final int DEPOSITION_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static RecordingSource valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static RecordingSource forNumber(int value) {
    switch (value) {
      case 0: return RECORDING_SOURCE_UNKNOWN;
      case 1: return UPLOAD;
      case 2: return DEPOSITION;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<RecordingSource>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      RecordingSource> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<RecordingSource>() {
          public RecordingSource findValueByNumber(int number) {
            return RecordingSource.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.parrothq.events_monitoring.v1.Expectations.getDescriptor().getEnumTypes().get(0);
  }

  private static final RecordingSource[] VALUES = values();

  public static RecordingSource valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private RecordingSource(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:events_monitoring.v1.RecordingSource)
}

