// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parrotschemas/events_monitoring/v1/expectations.proto

package com.parrothq.events_monitoring.v1;

/**
 * Protobuf enum {@code parrotschemas.events_monitoring.v1.RecordingType}
 */
public enum RecordingType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>RECORDING_TYPE_UNKNOWN = 0;</code>
   */
  RECORDING_TYPE_UNKNOWN(0),
  /**
   * <code>RESERVOIR = 1;</code>
   */
  RESERVOIR(1),
  /**
   * <code>CLIENT = 2;</code>
   */
  CLIENT(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>RECORDING_TYPE_UNKNOWN = 0;</code>
   */
  public static final int RECORDING_TYPE_UNKNOWN_VALUE = 0;
  /**
   * <code>RESERVOIR = 1;</code>
   */
  public static final int RESERVOIR_VALUE = 1;
  /**
   * <code>CLIENT = 2;</code>
   */
  public static final int CLIENT_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static RecordingType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static RecordingType forNumber(int value) {
    switch (value) {
      case 0: return RECORDING_TYPE_UNKNOWN;
      case 1: return RESERVOIR;
      case 2: return CLIENT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<RecordingType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      RecordingType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<RecordingType>() {
          public RecordingType findValueByNumber(int number) {
            return RecordingType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.parrothq.events_monitoring.v1.Expectations.getDescriptor().getEnumTypes().get(1);
  }

  private static final RecordingType[] VALUES = values();

  public static RecordingType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private RecordingType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:parrotschemas.events_monitoring.v1.RecordingType)
}

