// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: events_monitoring/v1/expectations.proto

package com.parrothq.events_monitoring.v1;

public interface RecordingPreprocessingStartedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:events_monitoring.v1.RecordingPreprocessingStarted)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 audio_length_seconds = 1;</code>
   * @return The audioLengthSeconds.
   */
  int getAudioLengthSeconds();

  /**
   * <code>.events_monitoring.v1.RecordingSource source = 2;</code>
   * @return The enum numeric value on the wire for source.
   */
  int getSourceValue();
  /**
   * <code>.events_monitoring.v1.RecordingSource source = 2;</code>
   * @return The source.
   */
  com.parrothq.events_monitoring.v1.RecordingSource getSource();
}
