// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: events_monitoring/v1/expectations.proto

package com.parrothq.events_monitoring.v1;

public interface RoughDraftStartedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:events_monitoring.v1.RoughDraftStarted)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 audio_length_seconds = 1;</code>
   * @return The audioLengthSeconds.
   */
  int getAudioLengthSeconds();
}
