// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: events_monitoring/v1/expectations.proto

package com.parrothq.events_monitoring.v1;

public interface StartDiarizedRoughDraftOrBuilder extends
    // @@protoc_insertion_point(interface_extends:events_monitoring.v1.StartDiarizedRoughDraft)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string recording_id = 1;</code>
   * @return The recordingId.
   */
  java.lang.String getRecordingId();
  /**
   * <code>string recording_id = 1;</code>
   * @return The bytes for recordingId.
   */
  com.google.protobuf.ByteString
      getRecordingIdBytes();

  /**
   * <code>int32 audio_length_seconds = 2;</code>
   * @return The audioLengthSeconds.
   */
  int getAudioLengthSeconds();
}
