# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events_monitoring/v1/expectations.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='events_monitoring/v1/expectations.proto',
  package='events_monitoring.v1',
  syntax='proto3',
  serialized_options=b'\n!com.parrothq.events_monitoring.v1P\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\'events_monitoring/v1/expectations.proto\x12\x14\x65vents_monitoring.v1\"=\n\x0fStartRoughDraft\x12\x14\n\x0crecording_id\x18\x01 \x01(\t\x12\x14\n\x0c\x61udio_length\x18\x02 \x01(\x05\"%\n\rEndRoughDraft\x12\x14\n\x0crecording_id\x18\x01 \x01(\tB%\n!com.parrothq.events_monitoring.v1P\x01\x62\x06proto3'
)




_STARTROUGHDRAFT = _descriptor.Descriptor(
  name='StartRoughDraft',
  full_name='events_monitoring.v1.StartRoughDraft',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='recording_id', full_name='events_monitoring.v1.StartRoughDraft.recording_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='audio_length', full_name='events_monitoring.v1.StartRoughDraft.audio_length', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=126,
)


_ENDROUGHDRAFT = _descriptor.Descriptor(
  name='EndRoughDraft',
  full_name='events_monitoring.v1.EndRoughDraft',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='recording_id', full_name='events_monitoring.v1.EndRoughDraft.recording_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=165,
)

DESCRIPTOR.message_types_by_name['StartRoughDraft'] = _STARTROUGHDRAFT
DESCRIPTOR.message_types_by_name['EndRoughDraft'] = _ENDROUGHDRAFT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartRoughDraft = _reflection.GeneratedProtocolMessageType('StartRoughDraft', (_message.Message,), {
  'DESCRIPTOR' : _STARTROUGHDRAFT,
  '__module__' : 'events_monitoring.v1.expectations_pb2'
  # @@protoc_insertion_point(class_scope:events_monitoring.v1.StartRoughDraft)
  })
_sym_db.RegisterMessage(StartRoughDraft)

EndRoughDraft = _reflection.GeneratedProtocolMessageType('EndRoughDraft', (_message.Message,), {
  'DESCRIPTOR' : _ENDROUGHDRAFT,
  '__module__' : 'events_monitoring.v1.expectations_pb2'
  # @@protoc_insertion_point(class_scope:events_monitoring.v1.EndRoughDraft)
  })
_sym_db.RegisterMessage(EndRoughDraft)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
